<div class="main-container columns-2">
    <div class="column column-1">
        <div class="panel">
            <h1>Headline</h1>
        </div>
    </div>
    <div class="column column-2">
        <div class="panel follow">
            <h2>Share</h2>

            <ol class="social-media">
                <li><a href="https://www.facebook.com/So-to-summarize-1139908682809955/" target="_blank"><i class="fa fa-facebook fa-fw" aria-hidden="true"></i></a></li>
                <li><a href="https://twitter.com/SoTosummarize" target="_blank"><i class="fa fa-twitter fa-fw" aria-hidden="true"></i></a></li>
            </ol>
        </div>
    </div>
</div>
