<?php
$this->layout()->setVariables([
    'htmlHeadTitle' => 'So, to summarize, ' . $summaryEntity->getTitle(),
]);
?>
<div class="main-container columns-2">
    <div class="column column-1">
        <div class="panel">
            <h1><?= $this->escape($summaryEntity->getTitle()); ?></h1>
        </div>
        <div class="panel">
            <h2>Titles</h1>

            <ol>
                <?php foreach ($titleVariations as $titleVariation): ?>
                    <li><?= $this->escape($titleVariation); ?></li>
                <?php endforeach ?>
            </ol>
        </div>
        <div class="panel">
            <h2>N-Grams</h2>

            <ol>
                <?php $count = 0;?>
                <?php foreach ($nGrams[4] as $key => $nGram): ?>
                    <li><?= $this->escape($key); ?></li>
                    <?php if ($count >= 9) {break;} ?>
                    <?php $count++; ?>
                <?php endforeach ?>
            </ol>

            <ol>
                <?php $count = 0;?>
                <?php foreach ($nGrams[3] as $key => $nGram): ?>
                    <li><?= $this->escape($key); ?></li>
                    <?php if ($count >= 9) {break;} ?>
                    <?php $count++; ?>
                <?php endforeach ?>
            </ol>

            <ol>
                <?php $count = 0;?>
                <?php foreach ($nGrams[2] as $key => $nGram): ?>
                    <li><?= $this->escape($key); ?></li>
                    <?php if ($count >= 9) {break;} ?>
                    <?php $count++; ?>
                <?php endforeach ?>
            </ol>

            <ol>
                <?php $count = 0;?>
                <?php foreach ($nGrams[1] as $key => $nGram): ?>
                    <li><?= $this->escape($key); ?></li>
                    <?php if ($count >= 9) {break;} ?>
                    <?php $count++; ?>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
    <div class="column column-2">
        <div class="panel follow">
            <h2>Details</h2>

            <p>
                <h3>Title</h3>
                <?= $this->escape($summaryEntity->getWebpage()->getTitle()); ?>
            </p>

            <p>
                <h3>URL</h3>
                <?= $this->escape($summaryEntity->getWebpage()->getUrl()); ?>
            </p>
        </div>
    </div>
</div>
