<?php
/**
$this->layout()->setVariables([
    'htmlHeadMetaOgDescription' => $this->summaryOg()->getOgDescription($summaryEntity),
    'htmlHeadMetaOgImage'       => $this->summaryOg()->getOgImage($summaryEntity),
    'htmlHeadMetaOgImageHeight' => $this->summaryOg()->getOgImageHeight($summaryEntity),
    'htmlHeadMetaOgImageWidth'  => $this->summaryOg()->getOgImageWidth($summaryEntity),
    'htmlHeadMetaOgType'        => $this->summaryOg()->getOgType($summaryEntity),
    'htmlHeadTitle'             => $this->summaryHtmlHeadTitle()->getHtmlHeadTitle($summaryEntity),
]);
$youtubeUrl = $sourceEntities[0]->url;
$queryString = parse_url($youtubeUrl)['query'];
parse_str($queryString, $result);
$youtubeVideoId = $result['v'];

$summaryFacebookShareUrlHelper = $this->summaryFacebookShareUrl();
$summaryTwitterShareUrlHelper  = $this->summaryTwitterShareUrl();

 */
?>
<div class="main-container columns-2">
    <div class="column column-1">
        <div class="panel">
            <h1>Wonderful</h1>
        </div>
    </div>
    <div class="column column-2">
        <div class="panel follow">
            <h2>Details</h2>

            <h3>URL</h3>
        </div>
    </div>
</div>
