<div class="main-container">
    <h1>Register</h1>

    <form action="/register" method="post">
        <p>
            Email<br>
            <input type="text" name="email">
        </p>

        <p>
            Username<br>
            <input type="text" name="username">
        </p>

        <p>
            Password<br>
            <input type="text" name="password">
        </p>

        <p>
            Confirm Password<br>
            <input type="text" name="confirm_password">
        </p>

        <p class="mb-0"><input type="submit" value="Register"></p>
    </form>

    <?php if ($message): ?>
        <p class="c-r"><?= $this->escape($message); ?></p>
    <?php endif ?>
</div>
