<div class="main-container">
    <h1>Login</h1>

    <form action="/login" method="post">
        <p>
            Username<br>
            <input type="text" name="username">
        </p>

        <p>
            Password<br>
            <input type="text" name="password">
        </p>

        <p class="mb-0"><input type="submit" value="Login"></p>
    </form>

    <?php if ($message): ?>
        <p class="c-r"><?= $this->escape($message); ?></p>
    <?php endif ?>
</div>
