<?php
$htmlHeadTitle = $htmlHeadTitle ?? 'So, to summarize, ...';
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta property="fb:app_id" content="1948337572154804">
<?php if (isset($htmlHeadMetaOgDescription)): ?>
        <meta property="og:description" content="<?= $this->escape($htmlHeadMetaOgDescription); ?>">
<?php endif ?>
<?php if (isset($htmlHeadMetaOgImage)): ?>
        <meta property="og:image" content="<?= $this->escape($htmlHeadMetaOgImage); ?>">
<?php endif ?>
<?php if (isset($htmlHeadMetaOgImageHeight)): ?>
        <meta property="og:image:height" content="<?= $this->escape($htmlHeadMetaOgImageHeight); ?>">
<?php endif ?>
<?php if (isset($htmlHeadMetaOgImageWidth)): ?>
        <meta property="og:image:width" content="<?= $this->escape($htmlHeadMetaOgImageWidth); ?>">
<?php endif ?>
        <meta property="og:site_name" content="So, to summarize, ...">
        <meta property="og:title" content="<?= $this->escape($htmlHeadTitle); ?>">
<?php if (isset($htmlHeadMetaOgType)): ?>
        <meta property="og:type" content="<?= $this->escape($htmlHeadMetaOgType); ?>">
<?php endif ?>
        <meta property="og:url" content="<?= $this->escape($this->serverUrl(true)); ?>">

        <title><?= $this->escape($htmlHeadTitle); ?></title>

        <link href="/css/style.css?v=2017122001" rel="stylesheet">
        <link href="/css/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <?php if ($_SERVER['HTTP_HOST'] == 'www.sotosummarize.com'): ?>
            <!-- Global site tag (gtag.js) - Google Analytics -->
            <script async src="https://www.googletagmanager.com/gtag/js?id=UA-42535259-30"></script>
            <script>
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());

                gtag('config', 'UA-42535259-30');
            </script>
        <?php endif ?>
    </head>
    <body>
        <header>
            <div class="container">
                <div class="left"><a href="/">So, to summarize, ...</a></div>
                <div class="right"><a href="/register">Register</a> or <a href="/login">Login</a></div>
            </div>
        </header>
        <main>
            <?= $this->content ?>
        </main>
        <footer>
            <div class="container">
                &copy; 2017
            </div>
        </footer>
    </body>
</html>
