<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>So, to summarize, ...</title>

        <link href="/css/style.css?v=2017120801" rel="stylesheet">
        <link href="/css/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <?php if ($_SERVER['HTTP_HOST'] == 'www.sotosummarize.com'): ?>
            <!-- Global site tag (gtag.js) - Google Analytics -->
            <script async src="https://www.googletagmanager.com/gtag/js?id=UA-42535259-30"></script>
            <script>
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());

                gtag('config', 'UA-42535259-30');
            </script>
        <?php endif ?>
    </head>
    <body>
        <header>
            <div class="container">
                <div class="left"><a href="/">So, to summarize, ...</a></div>
                <div class="right"><a href="/register">Register</a> or <a href="/login">Login</a></div>
            </div>
        </header>
        <main>
            <?= $this->content ?>
        </main>
        <footer>
            <div class="container">
                &copy; 2017
            </div>
        </footer>
    </body>
</html>
