<div class="main-container columns-2">
    <div class="column column-1">
        <div class="panel">
            <h1>Crawl</h1>

            <form action="/admin/crawl" method="post">
                URL: <input type="text" name="url">
                <input type="submit" value="Submit">
            </form>
        </div>
    </div>
    <div class="column column-2">
        <div class="panel">
            Wow.
        </div>
    </div>
</div>
