<div class="main-container columns-2">
    <div class="column column-1">
        <div class="panel">
            <h1>Crawl</h1>

            <form action="/admin/crawl" method="post">
                URL: <input type="text" name="url">
                <input type="submit" value="Submit">
            </form>

            <?php if (isset($webpageId)): ?>
                <p>
                    Successfully added URL.<br>
                    URL: <?= $this->escape($url); ?><br>
                    Webpage ID: <?= $this->escape($webpageId); ?>
                </p>
            <?php endif ?>
        </div>
    </div>
    <div class="column column-2">
        <div class="panel">
            Wow.
        </div>
    </div>
</div>
