<div class="main-container columns-2">
    <div class="column column-1">
        <div class="panel">
            <h1>Admin</h1>

            <h2>Summaries</h2>

            <ol>
                <?php foreach ($summaryEntities as $summaryEntity): ?>
                    <?php try {
                        $summaryEntityTitle = $summaryEntity->getTitle();
                    } catch (TypeError $typeError) {
                        $summaryEntityTitle = 'No title yet';
                    }
                    ?>
                    <li><?= $this->escape($summaryEntityTitle); ?></li>
                <?php endforeach ?>
            </ol>

            <p><a href="/admin/crawl">Crawl</a></p>
        </div>
    </div>
    <div class="column column-2">
        <div class="panel">
            Wow.
        </div>
    </div>
</div>
