<div class="main-container columns-2">
    <div class="column column-1">
        <div class="panel">
            <h1>Trending</h1>

            <ol class="articles">
                <li>
                    <div class="image"><img src="/images/pea.jpg" style="width: 200px;" alt="Vestibulum sed elementum diam"></div>
                    <div class="blurb">
                        <h3><a href="/summaries/1/Rob-Bliss-Uses-Amazon-Prime-to-Deliver-Goods-to-Homeless">Rob Bliss Uses Amazon Prime to Deliver Goods to Homeless</a></h3>
                        <div>In an experiment to see whether he could use his phone to deliver goods to homeless people, Rob Bliss used Amazon Prime to deliver socks, backpacks, long johns, and other goods to homeless people on the street.</div>
                    </div>
                </li>
                <li>
                    <div class="image"><img src="/images/pea.jpg" style="width: 200px;" alt="Vestibulum sed elementum diam"></div>
                    <div class="blurb">
                        <h3><a href="/">Vestibulum sed elementum diam</a></h3>
                        <div>Phasellus eu dolor consectetur, aliquam mauris eget, eleifend mauris. Integer eu risus gravida erat bibendum posuere quis vel nibh. Integer eu nisl vel nunc porttitor egestas nec quis dui. Vestibulum dapibus risus magna, sed ultricies leo luctus ut. Morbi varius est neque, sed rutrum mi porta vitae. Nullam sit amet nisi sollicitudin, efficitur arcu ut, interdum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div>
                    </div>
                </li>
                <li>
                    <div class="image"><img src="/images/pea.jpg" style="width: 200px;" alt="Vestibulum sed elementum diam"></div>
                    <div class="blurb">
                        <h3><a href="/">Vestibulum sed elementum diam</a></h3>
                        <div>Phasellus eu dolor consectetur, aliquam mauris eget, eleifend mauris. Integer eu risus gravida erat bibendum posuere quis vel nibh. Integer eu nisl vel nunc porttitor egestas nec quis dui. Vestibulum dapibus risus magna, sed ultricies leo luctus ut. Morbi varius est neque, sed rutrum mi porta vitae. Nullam sit amet nisi sollicitudin, efficitur arcu ut, interdum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div>
                    </div>
                </li>
                <li>
                    <div class="image"><img src="/images/pea.jpg" style="width: 200px;" alt="Vestibulum sed elementum diam"></div>
                    <div class="blurb">
                        <h3><a href="/">Vestibulum sed elementum diam</a></h3>
                        <div>Phasellus eu dolor consectetur, aliquam mauris eget, eleifend mauris. Integer eu risus gravida erat bibendum posuere quis vel nibh. Integer eu nisl vel nunc porttitor egestas nec quis dui. Vestibulum dapibus risus magna, sed ultricies leo luctus ut. Morbi varius est neque, sed rutrum mi porta vitae. Nullam sit amet nisi sollicitudin, efficitur arcu ut, interdum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div>
                    </div>
                </li>
                <li>
                    <div class="image"><img src="/images/pea.jpg" style="width: 200px;" alt="Vestibulum sed elementum diam"></div>
                    <div class="blurb">
                        <h3><a href="/">Vestibulum sed elementum diam</a></h3>
                        <div>Phasellus eu dolor consectetur, aliquam mauris eget, eleifend mauris. Integer eu risus gravida erat bibendum posuere quis vel nibh. Integer eu nisl vel nunc porttitor egestas nec quis dui. Vestibulum dapibus risus magna, sed ultricies leo luctus ut. Morbi varius est neque, sed rutrum mi porta vitae. Nullam sit amet nisi sollicitudin, efficitur arcu ut, interdum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div>
                    </div>
                </li>
            </ol>
        </div>
    </div>
    <div class="column column-2">
        <div class="panel follow">
            <h2>Follow</h2>

            <ol class="social-media">
                <li><a href="https://www.facebook.com/So-to-summarize-1139908682809955/" target="_blank"><i class="fa fa-facebook fa-fw" aria-hidden="true"></i></a></li>
                <li><a href="https://www.instagram.com/sotosummarize/" target="_blank"><i class="fa fa-instagram fa-fw" aria-hidden="true"></i></a></li>
                <li><a href="https://twitter.com/SoTosummarize" target="_blank"><i class="fa fa-twitter fa-fw" aria-hidden="true"></i></a></li>
            </ol>
        </div>
    </div>
</div>
