<div class="main-container columns-2">
    <div class="column column-1">
        <div class="panel">
            <h1>Trending</h1>

            <ol class="articles">
                <li>
                    <div class="image"><a href="/summaries/2/A-US-Fighter-Pilot-has-Spotted-a-UFO"><img src="/images/summaries/2/area-51.jpg" style="width: 200px;" alt="A US Fighter Pilot has Spotted a UFO"></a></div>
                    <div class="blurb">
                        <h3><a href="/summaries/2/A-US-Fighter-Pilot-has-Spotted-a-UFO">A US Fighter Pilot has Spotted a UFO</a></h3>
                        <div>
                            Pilot 1: It's a [expletive] drone, bro.<br>
                            Pilot 2: There's a whole fleet of them. Look on the ASA.<br>
                            Pilot 1: My gosh.<br>
                            Pilot 2: They're all going against the wind. The wind's 120 knots out of the west.<br>
                            Pilot 1: Look at that thing dude.<br>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="image"><a href="/summaries/1/Rob-Bliss-Uses-Amazon-Prime-to-Deliver-Goods-to-Homeless"><img src="/images/summaries/1/homeless.jpg" style="width: 200px;" alt="Rob Bliss Uses Amazon Prime to Deliver Goods to Homeless"></a></div>
                    <div class="blurb">
                        <h3><a href="/summaries/1/Rob-Bliss-Uses-Amazon-Prime-to-Deliver-Goods-to-Homeless">Rob Bliss Uses Amazon Prime to Deliver Goods to Homeless</a></h3>
                        <div>In an experiment to see whether he could use his phone to deliver goods to homeless people, Rob Bliss used Amazon Prime to deliver socks, backpacks, long johns, and other goods to homeless people on the street.</div>
                    </div>
                </li>
            </ol>
        </div>
    </div>
    <div class="column column-2">
        <div class="panel follow">
            <h2>Follow</h2>

            <ol class="social-media">
                <li><a href="https://www.facebook.com/So-to-summarize-1139908682809955/" target="_blank"><i class="fa fa-facebook fa-fw" aria-hidden="true"></i></a></li>
                <li><a href="https://www.instagram.com/sotosummarize/" target="_blank"><i class="fa fa-instagram fa-fw" aria-hidden="true"></i></a></li>
                <li><a href="https://twitter.com/SoTosummarize" target="_blank"><i class="fa fa-twitter fa-fw" aria-hidden="true"></i></a></li>
            </ol>
        </div>
    </div>
</div>
